### ISSUE TITLE
Get all creative ids

### ISSUE THREAD

**Issue by CharleoY** [faniAhmed/GoogleAdsTransparencyScraper#2]
Hi,

First of all, thanks for the great work. 

While playing with you code, it seems that it can only get the first 22 creatives, which is the number of ads in one request. But usually an advertisor tends to have more ads than that. I didn't find any of the code exploring this part. There will be a new parameter in the request for the rest of the page:

`f.req: {"2":40,"3":{"8":[2276],"12":{"1":"","2":true},"13":{"1":["AR03893175854238269441"]}},**"4":"CgoAP7zn/42TJjHHEhA61AJshH+nzstEgjsAAAAAGgn8+NdY+B5FumE="**,"7":{"1":1,"2":0,"3":2702}}`

Sadly I don't find approach to understand how "4":"CgoAP7zn/42TJjHHEhA61AJshH+nzstEgjsAAAAAGgn8+NdY+B5FumE=" is computed. 

Do you have any idea how to implement the function for retrieving the data in the rest of the pages?

Again, thanks for the great work.

**Comment by faniAhmed** [comment]
Hi,
I totally forgot about this, I had it in mind. I will try to update the code in 2 to 3 days. 
Will let you know once I add this feature

**Comment by CharleoY** [comment]
Hi, I have found that in each of the request at key "2" will store the next page identifier.

**Comment by faniAhmed** [comment]
Thanks, I will have a check and implement it int the module, or you can create a pull requests

**Comment by faniAhmed** [comment]
Now the function gets creatives based on count argument provided to the function
